import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div style={{ height: "100vh", padding: "20px", backgroundColor: "#232323", color: "white" }}>
      <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>
      <p style={{ fontSize: "18px", marginBottom: "30px" }}>
        This project was generated By{" "}
        <a href="https://www.covrize.com" style={{ color: "#87CEFA", textDecoration: "none" }}>
          EduVista
        </a>
        . Quickly use below links to navigate through all pages.
      </p>
      <ul style={{ listStyle: "none", padding: "0" }}>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/" style={{ color: "#87CEFA", textDecoration: "none" }}>
            EduviCoursesDetails
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/eduvishop" style={{ color: "#87CEFA", textDecoration: "none" }}>
            EduviShop
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/eduvicourses" style={{ color: "#87CEFA", textDecoration: "none" }}>
            EduviCourses
          </Link>
        </li>
        <li style = {{marginBottom: "10px" }}>
          <link to="/eduvicoursepricing" style={{ color: "#87CEFA", textDecoration: "none" }}>
            EduviCoursesPricing
          </link>
        </li>
        <li style = {{marginBottom: "10px" }}>
          <link to="/eduvijoinasteacher" style={{ color: "#87CEFA", textDecoration: "none" }}>
            EduviJoinAsTeacher
          </link>
        </li>
        <li style = {{marginBottom: "10px" }}>
          <link to="/allmentors" style={{ color: "#87CEFA", textDecoration: "none" }}>
            All Mentors
          </link>
        </li>
        <li style = {{marginBottom: "10px" }}>
          <link to="/singlementordetails" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Singlementordetails
          </link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
